"""
Mods vendidos pelas Syndicates (tela de Offerings).

Fonte: WARFRAME Wiki, Module:Vendors/data. Os nomes restringem o pool de
matching do OCR (app/captura/mods_ocr.py) — essa tela só mostra mods de
syndicate, então restringir elimina falsos positivos do reconhecimento.
"""

MODS_DE_SYNDICATE: dict[str, tuple[str, ...]] = {
    'Arbiters of Hexis': (
        'Assimilate', 'Avenging Truth', 'Axios Javelineers', 'Blade of Truth', 
        'Calm & Frenzy', 'Capacitance', 'Cataclysmic Continuum', 'Cathode Current', 
        'Celestial Stomp', 'Chaos Sphere', 'Chromatic Blade', 'Coil Recharge', 
        'Conductive Sphere', 'Damage Decoy', "Desiccation's Curse", 'Duality', 
        'Elemental Sandstorm', 'Elusive Retribution', 'Endless Lullaby', 'Energy Transfer', 
        'Enveloping Cloud', 'Explosive Legerdemain', 'Furious Javelin', 'Gilded Truth', 
        'Hall of Malevolence', 'Hushed Invisibility', 'Intrepid Stand', 'Irradiating Disarm', 
        "Jade's Judgment", 'Kumihimo Loading', 'Lasting Covenant', 'Mach Crash', 
        'Mending Splinters', 'Mind Freak', 'Negation Armor', 'Noctua Swarm', 
        "Omikuji's Fortune", 'Pacifying Bolts', 'Peaceful Provocation', 'Primal Rage', 
        'Radiant Finish', 'Reactive Storm', 'Repair Dispensary', 'Reverse Rotorswell', 
        'Rift Haven', 'Rift Torrent', 'Rising Storm', 'Safeguard Switch', 
        'Savior Decoy', 'Seeking Shuriken', 'Shattered Storm', 'Shock Trooper', 
        'Shocking Speed', 'Smoke Shadow', 'Spectrosiphon', 'Stinging Truth', 
        'Surging Dash', 'Teleport Rush', 'Temporal Artillery', 'Temporal Erosion', 
        'Tharros Lethality', 'Thermal Transfer', 'Total Eclipse', 'Transistor Shield', 
        'Tribunal', 'Warding Thurible', "Warrior's Rest", 
    ),
    'Cephalon Suda': (
        'Aegis Gale', 'Afterburn', 'Antimatter Absorb', 'Balefire Surge', 
        'Biting Frost', 'Blazing Pillage', 'Blinding Reave', 'Cataclysmic Continuum', 
        'Cataclysmic Gate', 'Chilling Globe', 'Concentrated Arrow', 'Conductor', 
        'Controlled Slide', 'Critical Surge', 'Dark Propagation', 'Divine Retribution', 
        'Empowered Quiver', 'Enduring Bastille', 'Entropy Burst', 'Entropy Detonation', 
        'Entropy Flight', 'Entropy Spike', 'Escape Velocity', 'Everlasting Ward', 
        'Explosive Legerdemain', 'Freeze Force', 'Fused Crucible', 'Fused Reservoir', 
        'Guardian Armor', 'Guided Effigy', 'Hall of Malevolence', 'Ice Wave Impedance', 
        'Icy Avalanche', 'Infiltrate', 'Loyal Merulina', 'Merulina Guardian', 
        'Mesmer Shield', 'Molecular Fission', 'Neutron Star', 'Noctua Swarm', 
        'Partitioned Mallet', 'Photon Repeater', 'Piercing Navigator', 'Pilfering Swarm', 
        'Pyroclastic Flow', 'Razor Mortar', 'Reaping Chakram', 'Resonance', 
        'Resonating Quake', 'Rift Haven', 'Rift Torrent', 'Rousing Plunder', 
        'Safeguard', 'Savage Silence', 'Shadow Haze', 'Sonic Fracture', 
        'Surging Blades', 'Tesla Bank', 'The Relentless Lost', 'Thrall Pact', 
        'Tidal Impunity', 'Total Eclipse', 'Untime Rift', 'Vampiric Grasp', 
        'Vexing Retaliation', 'Viral Tempest', 'Wrecking Wall', 
    ),
    'Conclave': (
        'Adept Surge', 'Afterburn', 'Agile Aim', 'Air Recon', 
        'Air Thrusters', 'Anti-Flak Plating', 'Anticipation', 'Antimatter Mine', 
        'Apex Predator', 'Argent Scourge', 'Armored Acrobatics', 'Armored Evade', 
        'Armored Recovery', 'Biting Piranha', 'Bounty Hunter', 'Broad Eye', 
        'Calculated Spring', 'Calculated Victory', 'Celestial Nightfall', 'Comet Rounds', 
        'Counterweight', 'Crash Shot', 'Crashing Havoc', 'Crashing Timber', 
        'Cunning Aspect', 'Deceptive Bond', 'Defiled Reckoning', 'Discharge Strike', 
        'Dividing Blades', 'Double-Barrel Drift', 'Eject Magazine', 'Explosive Demise', 
        'Fateful Truth', 'Flak Shot', 'Follow Through', 'Full Capacity', 
        'Gun Glide', 'Heartseeker', 'Hysterical Fixation', 'Ice Wave Impedance', 
        'Impaler Munitions', 'Impenetrable Offense', 'Iron Shrapnel', 'Kinetic Collision', 
        'Lashing Coil', 'Last Herald', 'Lie In Wait', 'Loaded Capacity', 
        'Lock and Load', 'Loose Chamber', 'Loose Hatch', 'Loose Magazine', 
        'Mafic Rain', 'Martial Fury', 'Maximum Capacity', "Mesa's Waltz", 
        'Meteor Munitions', 'Momentary Pause', 'Night Stalker', 'No Current Leap', 
        'Noble Cadence', 'Overcharge Detectors', 'Overcharged', 'Overview', 
        'Piercing Fury', 'Power of Three', 'Prism Guard', 'Prize Kill', 
        'Purging Slash', 'Purifying Flames', 'Push & Pull', 'Quaking Hand', 
        'Quick Charge', 'Razor Munitions', 'Recharge Barrier', 'Recover', 
        'Recuperate', 'Reflex Draw', 'Relentless Assault', 'Rending Wind', 
        'Rime Vault', 'Ripper Rounds', 'Rising Skill', 'Rising Steel', 
        'Rumbled', 'Sapping Reach', 'Scarlet Hurricane', 'Searing Leap', 
        'Serrated Edges', 'Serrated Rounds', 'Shadow Harvest', 'Sharpened Blade', 
        'Shield Overload', 'Shred Shot', 'Signal Flare', 'Singularity', 
        'Snap Shot', 'Soft Hands', 'Spring-Loaded Broadhead', 'Spry Sights', 
        'Stand Ground', 'Star Divide', 'Strafing Slide', 'Surplus Diverters', 
        'Sword Alone', 'Tactical Reload', 'Tainted Hydra', 'Tear Gas', 
        'Tempered Bound', 'Twitch', 'Vanquished Prey', 'Venomous Rise', 
        'Vicious Approach', 'Voltaic Lance', 'Ward Recovery', 
    ),
    'New Loka': (
        'Abating Link', 'Airburst Rounds', 'Anchored Glide', 'Assimilate', 
        'Axios Javelineers', 'Beguiling Lantern', 'Bright Purity', 'Calm & Frenzy', 
        'Cataclysmic Gate', 'Celestial Stomp', "Champion's Blessing", 'Chaos Sphere', 
        'Conductor', 'Counter Pulse', 'Critical Surge', 'Disarming Purity', 
        'Duality', 'Elusive Retribution', 'Endless Lullaby', 'Energy Transfer', 
        'Enraged', 'Enveloping Cloud', 'Eternal War', 'Fracturing Crush', 
        'Funnel Clouds', 'Fused Reservoir', 'Greedy Pull', 'Hallowed Eruption', 
        'Hallowed Reckoning', 'Hysterical Assault', 'Intrepid Stand', 'Ironclad Flight', 
        'Jet Stream', 'Kumihimo Loading', 'Lasting Purity', 'Lingering Transmutation', 
        'Loyal Merulina', 'Magnetized Discharge', 'Mending Splinters', 'Merulina Guardian', 
        'Mind Freak', "Omikuji's Fortune", 'Pacifying Bolts', 'Partitioned Mallet', 
        'Peaceful Provocation', 'Phoenix Renewal', 'Pilfering Swarm', 'Pool of Life', 
        'Primal Rage', 'Prolonged Paralysis', 'Razorwing Blitz', 'Reactive Storm', 
        'Rhythm Guard', 'Rousing Plunder', 'Shattered Storm', 'Smite Infusion', 
        'Spectrosiphon', 'Spellbound Harvest', 'Surging Blades', 'Swift Bite', 
        'Swing Line', 'Target Fixation', 'Tharros Lethality', 'Tidal Impunity', 
        'Valence Formation', 'Vampire Leech', 'Viral Tempest', 'Volatile Recompense', 
        'Winds of Purity', 'Wrath of Ukko', 
    ),
    'Red Veil': (
        'Accumulating Whipclaw', 'Airburst Rounds', 'Anchored Glide', 'Ballistic Bullseye', 
        'Beguiling Lantern', 'Blending Talons', 'Blood Forge', 'Capacitance', 
        'Catapult', 'Contagion Cloud', 'Creeping Terrify', 'Damage Decoy', 
        'Despoil', 'Dread Ward', 'Eroding Blight', 'Exothermic', 
        'Fireball Frenzy', 'Funnel Clouds', 'Gastro', 'Gleaming Blight', 
        'Gourmand', 'Healing Flame', 'Hearty Nourishment', 'Hushed Invisibility', 
        'Immolated Radiance', 'Ironclad Flight', 'Irradiating Disarm', "Jade's Judgment", 
        'Jet Stream', 'Lasting Covenant', 'Lingering Transmutation', "Mesa's Waltz", 
        'Muzzle Flash', 'Ore Gaze', 'Path of Statues', 'Pilfering Strangledome', 
        'Prey of Dynar', 'Prismatic Companion', 'Razorwing Blitz', 'Recrystalize', 
        'Regenerative Molt', 'Reroot Rampage', 'Revealing Spores', 'Rising Storm', 
        'Rubble Heap', 'Safeguard Switch', 'Savior Decoy', 'Seeking Shuriken', 
        'Shield of Shadows', 'Shock Trooper', 'Shocking Speed', 'Smoke Shadow', 
        'Soul Survivor', 'Spectral Spirit', 'Spellbound Harvest', 'Staggering Shield', 
        'Stockpiled Blight', 'Swift Bite', 'Target Fixation', 'Tectonic Fracture', 
        'Teleport Rush', 'Titanic Rumbler', 'Toxic Blight', 'Transistor Shield', 
        'Tribunal', "Ulfrun's Endurance", 'Valence Formation', 'Venari Bodyguard', 
        'Venom Dose', 'Warding Thurible', "Warrior's Rest", 
    ),
    'Steel Meridian': (
        'Abundant Mutation', 'Accumulating Whipclaw', 'Antimatter Absorb', 'Ballistic Bullseye', 
        'Biting Frost', 'Blending Talons', 'Blood Forge', 'Catapult', 
        'Chilling Globe', 'Chromatic Blade', 'Contagion Cloud', 'Controlled Slide', 
        'Divine Retribution', 'Dread Ward', 'Escape Velocity', 'Exothermic', 
        'Fireball Frenzy', 'Freeze Force', 'Furious Javelin', 'Fused Crucible', 
        'Gastro', 'Gourmand', 'Hallowed Eruption', 'Hallowed Reckoning', 
        'Healing Flame', 'Hearty Nourishment', 'Ice Wave Impedance', 'Icy Avalanche', 
        'Immolated Radiance', 'Insatiable', 'Iron Shrapnel', 'Ironclad Charge', 
        'Justice Blades', 'Larva Burst', "Mesa's Waltz", 'Molecular Fission', 
        'Muzzle Flash', 'Neutralizing Justice', 'Neutron Star', 'Ore Gaze', 
        'Parasitic Vitality', 'Path of Statues', 'Phoenix Renewal', 'Piercing Roar', 
        'Pilfering Strangledome', 'Prey of Dynar', 'Prismatic Companion', 'Pyroclastic Flow', 
        'Radiant Finish', 'Reaping Chakram', 'Recrystalize', 'Regenerative Molt', 
        'Reinforcing Stomp', 'Revealing Spores', 'Rhythm Guard', 'Rubble Heap', 
        'Safeguard', 'Scattered Justice', 'Shattering Justice', 'Smite Infusion', 
        'Staggering Shield', 'Surging Dash', 'Tectonic Fracture', 'Teeming Virulence', 
        'The Relentless Lost', 'Titanic Rumbler', "Ulfrun's Endurance", 'Untime Rift', 
        'Vampiric Grasp', 'Venari Bodyguard', 'Venom Dose', 'Volatile Recompense', 
        'Wrath of Ukko', 'Wrecking Wall', 
    ),
    'The Perrin Sequence': (
        'Abating Link', 'Abundant Mutation', 'Aegis Gale', 'Afterburn', 
        'Balefire Surge', 'Blazing Pillage', 'Blinding Reave', 'Cathode Current', 
        "Champion's Blessing", 'Coil Recharge', 'Concentrated Arrow', 'Conductive Sphere', 
        'Counter Pulse', 'Creeping Terrify', 'Dark Propagation', 'Deadly Sequence', 
        "Desiccation's Curse", 'Despoil', 'Elemental Sandstorm', 'Empowered Quiver', 
        'Enraged', 'Eternal War', 'Everlasting Ward', 'Fracturing Crush', 
        'Greedy Pull', 'Guardian Armor', 'Guided Effigy', 'Hysterical Assault', 
        'Infiltrate', 'Insatiable', 'Iron Shrapnel', 'Ironclad Charge', 
        'Larva Burst', 'Mach Crash', 'Magnetized Discharge', 'Mesmer Shield', 
        'Negation Armor', 'Parasitic Vitality', 'Photon Repeater', 'Piercing Navigator', 
        'Piercing Roar', 'Pool of Life', 'Prolonged Paralysis', 'Razor Mortar', 
        'Reinforcing Stomp', 'Repair Dispensary', 'Repelling Bastille', 'Reroot Rampage', 
        'Resonance', 'Resonating Quake', 'Reverse Rotorswell', 'Savage Silence', 
        'Sequence Burn', 'Shadow Haze', 'Shield of Shadows', 'Sonic Fracture', 
        'Soul Survivor', 'Spectral Spirit', 'Swing Line', 'Teeming Virulence', 
        'Temporal Artillery', 'Temporal Erosion', 'Tesla Bank', 'Thermal Transfer', 
        'Thrall Pact', 'Toxic Sequence', 'Vampire Leech', 'Vexing Retaliation', 
        'Voltage Sequence', 
    ),
}


MODS_SINDICATO_POR_NOME: dict[str, tuple[str, ...]] = {
    # nome sem espaços e casefolded (mesma normalização do OCR/comparador) ->
    # syndicates que vendem esse mod (pode haver mais de uma).
    "".join(nome.split()).casefold(): tuple(
        sind
        for sind, _nomes in MODS_DE_SYNDICATE.items()
        if nome in _nomes
    )
    for nome in sorted({_n for _ns in MODS_DE_SYNDICATE.values() for _n in _ns})
}

